Input Notebook:  dms-vep-pipeline-3/notebooks/avg_func_effects.ipynb
Output Notebook: results/notebooks/avg_func_effects_293T_entry.ipynb
Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   5%|▌         | 1/20 [00:00<00:11,  1.58cell/s]Executing:  10%|█         | 2/20 [00:01<00:10,  1.79cell/s]Executing:  45%|████▌     | 9/20 [00:01<00:01, 10.14cell/s]Executing:  60%|██████    | 12/20 [00:01<00:00, 11.70cell/s]Executing:  75%|███████▌  | 15/20 [00:01<00:00,  8.89cell/s]Executing:  85%|████████▌ | 17/20 [00:02<00:00,  8.37cell/s]Executing:  95%|█████████▌| 19/20 [00:03<00:00,  4.97cell/s]Executing:  95%|█████████▌| 19/20 [00:03<00:00,  5.35cell/s]
Traceback (most recent call last):
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/bin/papermill", line 10, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/papermill/cli.py", line 235, in papermill
    execute_notebook(
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/sooriyakks/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/pandas/core/indexes/base.py:3805, in Index.get_loc(self, key)
   3804 try:
-> 3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:

File index.pyx:167, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:196, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7081, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7089, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'effect'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[10], line 9
      5 print(f"\n\nPlotting {phenotype} and saving to {plotfile}")
      7 df = avg_func_effects.query("phenotype == @phenotype")
----> 9 chart = polyclonal.plot.lineplot_and_heatmap(
     10     data_df=df,
     11     stat_col="effect",
     12     category_col="phenotype",
     13     **plot_kwargs,
     14 )
     16 chart.save(plotfile)
     18 display(chart)

File ~/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/polyclonal/plot.py:948, in lineplot_and_heatmap(data_df, stat_col, category_col, alphabet, sites, addtl_tooltip_stats, addtl_slider_stats, addtl_slider_stats_as_max, addtl_slider_stats_hide_not_filter, init_floor_at_zero, init_site_statistic, cell_size, lineplot_width, lineplot_height, site_zoom_bar_width, site_zoom_bar_color_col, plot_title, show_single_category_label, category_colors, heatmap_negative_color, heatmap_color_scheme, heatmap_color_scheme_mid_0, heatmap_lims_from_slider_init, heatmap_max_at_least, heatmap_min_at_least, heatmap_max_fixed, heatmap_min_fixed, site_zoom_bar_color_scheme, slider_binding_range_kwargs, hide_color, show_zoombar, show_lineplot, show_heatmap, scale_stat_col, rename_stat_col, rename_std, sites_to_show)
    943 for slider_stat, slider in sliders.items():
    944     if slider_stat == "_stat_site_max":
    945         base_chart = base_chart.transform_calculate(
    946             _stat_not_hidden=alt.expr.if_(
    947                 alt.datum["_stat_hide"],
--> 948                 float(data_df[stat_col].min()),
    949                 alt.datum["_stat"],
    950             ),
    951         ).transform_joinaggregate(
    952             _stat_site_max="max(_stat_not_hidden)",
    953             groupby=["site"],
    954         )
    955         base_chart = base_chart.transform_filter(
    956             (alt.datum[slider_stat] >= (slider - 1e-6))  # round tol
    957             | ~alt.expr.isFinite(alt.datum[slider_stat])  # do not filter null
    958         )
    959     elif slider_stat not in addtl_slider_stats_hide_not_filter:

File ~/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/pandas/core/frame.py:4102, in DataFrame.__getitem__(self, key)
   4100 if self.columns.nlevels > 1:
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):
   4104     indexer = [indexer]

File ~/miniconda3/envs/dms-vep-pipeline-3/lib/python3.12/site-packages/pandas/core/indexes/base.py:3812, in Index.get_loc(self, key)
   3807     if isinstance(casted_key, slice) or (
   3808         isinstance(casted_key, abc.Iterable)
   3809         and any(isinstance(x, slice) for x in casted_key)
   3810     ):
   3811         raise InvalidIndexError(key)
-> 3812     raise KeyError(key) from err
   3813 except TypeError:
   3814     # If we have a listlike key, _check_indexing_error will raise
   3815     #  InvalidIndexError. Otherwise we fall through and re-raise
   3816     #  the TypeError.
   3817     self._check_indexing_error(key)

KeyError: 'effect'

